-- MySQL Script generated by MySQL Workbench
-- Wed Feb  1 13:14:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema datadc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema datadc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datadc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `datadc` ;

-- -----------------------------------------------------
-- Table `datadc`.`comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datadc`.`comics` (
  `id_comics` INT NOT NULL AUTO_INCREMENT,
  `name_comics` VARCHAR(45) NOT NULL,
  `apparition` DATE NOT NULL,
  `img_comics` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_comics`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datadc`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datadc`.`character` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL DEFAULT 'character',
  `name` VARCHAR(45) NOT NULL,
  `bio` VARCHAR(255) NOT NULL,
  `img` VARCHAR(128) NOT NULL,
  `id_comics` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_comics_idx` (`id_comics` ASC) VISIBLE,
  CONSTRAINT `id_comics`
    FOREIGN KEY (`id_comics`)
    REFERENCES `datadc`.`comics` (`id_comics`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
